version: 2
jobs:
  build:
    docker:
      - image: centos:centos6

  steps:
      - checkout
      # Enable EPEL for Node.js
      - run: rpm -Uvh http://download.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rp

      # Install Node...
      -run: yum install -y npm

      # Copy app to /src
      #COPY . /src

      # Install app and dependencies into /src
      -run: cd /src; npm install

      #EXPOSE 8080

      #CMD cd /src && node ./app.js
