version: 2
jobs:
  build:
    docker:
      - image: centos:centos6
    steps:
      - checkout
      - run: rpm -Uvh http://download.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm
      - run: yum install -y npm
      - run:
          command: |
              echo "creating new folder"
              mkdir -p /src
              echo "Copying file(s) ..."
              cp -r * /src
      - run:
          #this displays the github repo files
          command: ls -al

      #      cd /src
      #- run: npm install
      

